In [9]:
import tensorflow as tf

In [10]:
print('tensorflow version', tf.__version__)

x = [[3.]]
y = [[5.]]
print('Result: {}'.format(tf.matmul(x, y)))

tensorflow version 2.11.0
Result: [[15.]]


In [11]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [12]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [13]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
rank2_tensor.shape

TensorShape([2, 2])

In [15]:
tensor1 = tf.ones([1, 2, 3])  # tf.ones() creates a shape [1, 2, 3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2, 3, 1])  # reshape existing data to shape [2, 3, 1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place, this will 
                                        # reshape the tensor to [3, 2]
                                        
# The number of elements in the reshaped tensor MUST match the number in the original

In [16]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [20]:
with tf.Session() as sess:  # creates a session using the default graph
    tensor.eval()  # tensor will of course be the name of your tensor

AttributeError: module 'tensorflow' has no attribute 'Session'